name: Linting

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup
      run: |
        python -m pip install --upgrade pip
        for file in requirements/* ; do
            pip install -r "$file"
        done
    - name: Lint
      run: |
        pylint source
      env:
          PYTHONPATH: source